#!/bin/bash

if [ $USE_DEV_MODE = "true" ];
  then nodemon --exec python -u main.py $POLLING_FREQ $ENTITIES_PER_ITERATION $ROUTING_KEY_GEO_DATA_UPDATE $RABBITMQ_DEFAULT_VHOST $RABBITMQ_DEFAULT_USER $RABBITMQ_DEFAULT_PASS $EXT_PORT_API_GIS $API_PORT;
  else python -u main.py $POLLING_FREQ $ENTITIES_PER_ITERATION $ROUTING_KEY_GEO_DATA_UPDATE $RABBITMQ_DEFAULT_VHOST $RABBITMQ_DEFAULT_USER $RABBITMQ_DEFAULT_PASS $EXT_PORT_API_GIS $API_PORT;
fi